apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: supersets.helm.operator-sdk
spec:
  group: helm.operator-sdk
  names:
    kind: Superset
    listKind: SupersetList
    plural: supersets
    singular: superset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
