apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: superset-operator
  template:
    metadata:
      labels:
        name: superset-operator
    spec:
      serviceAccountName: superset-operator
      containers:
        - name: superset-operator
          # Replace this with the built image name
          image: gcr.io/codelity-co/superset-operator:v0.4.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "superset-operator"
